version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: .env
    ports:
      - 8020:8000
    depends_on:
      - db

volumes:
  postgres_data:
